# Generated by Django 3.2.5 on 2022-09-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_tbl',
            old_name='phone',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='data_tbl',
            old_name='email',
            new_name='age',
        ),
    ]
