# Generated by Django 3.2.15 on 2022-09-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_auto_20220921_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_tbl',
            name='age',
            field=models.IntegerField(max_length=50),
        ),
    ]
