# Generated by Django 3.2.15 on 2022-09-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_alter_data_tbl_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_tbl',
            name='age',
            field=models.IntegerField(),
        ),
    ]
