# Generated by Django 3.2.15 on 2022-09-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='age',
            field=models.CharField(max_length=100),
        ),
    ]
